package compaction

import (
	"bytes"
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"runtime"
	"runtime/pprof"
	"strings"
	"syscall"
	"time"

	"github.com/basekick-labs/arc/internal/storage"
	"github.com/rs/zerolog"

	// Import DuckDB driver for subprocess
	_ "github.com/duckdb/duckdb-go/v2"
)

// SubprocessJobConfig is the serializable configuration passed to the subprocess.
// It contains all information needed to run a compaction job in isolation.
type SubprocessJobConfig struct {
	Database      string   `json:"database"`
	Measurement   string   `json:"measurement"`
	PartitionPath string   `json:"partition_path"`
	Files         []string `json:"files"`
	Tier          string   `json:"tier"`
	TempDirectory string   `json:"temp_directory"`
	// BatchNumber is the 1-based index of this batch within its partition.
	// Carried through so the subprocess can disambiguate the output filename
	// between sibling batches (see Job.compactFiles). Zero means the job was
	// not produced by SplitCandidateIntoBatches.
	BatchNumber int `json:"batch_number,omitempty"`
	// ParentFinalizesManifest makes the subprocess LEAVE the crash-recovery
	// storage manifest in place on full success, so the parent can mark
	// edge-sync receipts for the consumed inputs and only then delete the
	// manifest itself (#619). Without this a parent crash between subprocess
	// success and receipt marking silently loses the marks: the sync
	// protocol later forgets the "stale" receipts and re-accepts re-uploaded
	// raws next to the compacted output — permanent duplication. With it, a
	// surviving manifest re-fires the marks through recovery (idempotent).
	ParentFinalizesManifest bool     `json:"parent_finalizes_manifest,omitempty"`
	SortKeys                []string `json:"sort_keys"`    // Sort keys for ORDER BY in compaction
	MemoryLimit             string   `json:"memory_limit"` // DuckDB memory limit (e.g., "8GB")
	// Threads is the DuckDB thread count for this subprocess. 0 means leave
	// DuckDB at its own default, which is the container's CPU quota where there
	// is one and all cores where there is not — the parent normally sends the
	// resolved compaction.threads value, so 0 only occurs for callers that
	// predate the field.
	Threads int `json:"threads,omitempty"`

	// Storage configuration
	StorageType   string `json:"storage_type"`   // "local" or "s3"
	StorageConfig string `json:"storage_config"` // JSON-encoded storage-specific config

	// Phase 4: cluster-mode completion-manifest handoff. When CompletionDir
	// is non-empty, the job writes a local-disk CompletionManifest that the
	// parent-side CompletionWatcher picks up and applies to the Raft manifest.
	// PartitionTime is the tier-scanner's authoritative timestamp for the
	// partition — bridged into raft.FileEntry.PartitionTime so peers know
	// which hour/day this compacted file belongs to.
	// JobID is generated by the parent (not NewJob) so both sides agree on
	// the completion-manifest filename. Empty values disable the feature.
	JobID         string `json:"job_id,omitempty"`
	CompletionDir string `json:"completion_dir,omitempty"`
	// No omitempty: a value time.Time is never omitted by encoding/json (#546),
	// so the tag was a no-op. A zero PartitionTime is a real "feature disabled"
	// sentinel checked via IsZero, and this is internal parent↔subprocess IPC,
	// not a user-facing field — matches the plain tag on completion.go's twin.
	PartitionTime time.Time `json:"partition_time"`
}

// SubprocessJobResult is returned by the subprocess via stdout as JSON.
// It contains the outcome of the compaction job.
type SubprocessJobResult struct {
	Success        bool   `json:"success"`
	Error          string `json:"error,omitempty"`
	FilesCompacted int    `json:"files_compacted"`
	BytesBefore    int64  `json:"bytes_before"`
	BytesAfter     int64  `json:"bytes_after"`
	OutputFile     string `json:"output_file,omitempty"`
	// CompactedInputs is the set of source files the job actually consumed
	// and deleted (validated inputs only — corrupted files are skipped and
	// LEFT in storage, and must keep their normal edge-sync receipts). The
	// parent's consumed-inputs observer marks the matching receipts (#619).
	CompactedInputs []string `json:"compacted_inputs,omitempty"`
	// ManifestPath is the crash-recovery storage manifest the subprocess
	// left in place under ParentFinalizesManifest; empty otherwise. The
	// parent deletes it after receipt marking commits.
	ManifestPath string `json:"manifest_path,omitempty"`
}

// RunSubprocessJob is called from the subprocess to execute compaction.
// It creates a new DuckDB connection, runs the job, and returns the result.
// When this function returns and the subprocess exits, all DuckDB memory is released.
//
// Memory profiling: Set ARC_COMPACTION_PROFILE=1 to enable heap profiling.
// Profiles are written to /tmp/arc_compaction_heap_before.pprof and /tmp/arc_compaction_heap_after.pprof
func RunSubprocessJob(config *SubprocessJobConfig) (*SubprocessJobResult, error) {
	// Setup logging to stderr (stdout is reserved for result JSON)
	logger := zerolog.New(os.Stderr).With().Timestamp().
		Str("component", "compaction-subprocess").
		Str("partition", config.PartitionPath).
		Logger()

	// Check if profiling is enabled
	profilingEnabled := os.Getenv("ARC_COMPACTION_PROFILE") == "1"
	if profilingEnabled {
		logger.Info().Msg("Memory profiling enabled - writing heap profiles to /tmp/")
		logMemStats(logger, "BEFORE compaction")
	}

	logger.Info().Msg("Starting compaction subprocess")

	// Create storage backend from config
	backend, err := createStorageBackendFromConfig(config, logger)
	if err != nil {
		return nil, fmt.Errorf("failed to create storage backend: %w", err)
	}
	defer backend.Close()

	// Create temporary DuckDB connection (in-memory)
	// This connection will be fully released when the subprocess exits
	db, err := sql.Open("duckdb", "")
	if err != nil {
		return nil, fmt.Errorf("failed to open duckdb: %w", err)
	}
	defer db.Close()

	// Pin the session time zone to UTC (#682), mirroring the query engine's
	// pin: the dedup path TRY_CASTs naive time strings to TIMESTAMPTZ, and
	// under a host-zone session a non-UTC host would permanently rewrite
	// those instants shifted by the UTC offset during compaction. Hard-fail:
	// compacting with a wrong zone corrupts data, not just query results.
	if _, err := db.Exec("SET TimeZone='UTC'"); err != nil {
		return nil, fmt.Errorf("failed to pin compaction DuckDB TimeZone to UTC: %w", err)
	}

	// Set DuckDB memory limit from config. Exceeding it makes DuckDB spill to
	// its temp_directory (configured below) instead of OOMing the process.
	if config.MemoryLimit != "" {
		if _, err := db.Exec(fmt.Sprintf("SET memory_limit='%s'", escapeSQLString(config.MemoryLimit))); err != nil {
			logger.Warn().Err(err).Str("limit", config.MemoryLimit).Msg("Failed to set DuckDB memory limit")
		} else {
			logger.Info().Str("limit", config.MemoryLimit).Msg("DuckDB memory limit configured")
		}
	}

	// Cap DuckDB threads. Without this every subprocess uses all cores, so
	// concurrent compaction jobs compete with the parent's ingest/query work —
	// and sort/scan buffers scale with threads, so this also bounds memory.
	if config.Threads > 0 {
		if _, err := db.Exec(fmt.Sprintf("SET threads=%d", config.Threads)); err != nil {
			logger.Warn().Err(err).Int("threads", config.Threads).Msg("Failed to set DuckDB thread count")
		} else {
			logger.Info().Int("threads", config.Threads).Msg("DuckDB thread count configured")
		}
	}

	// Point DuckDB's spill directory inside this job's own temp dir. An
	// in-memory DuckDB defaults temp_directory to ".tmp" relative to the
	// PARENT's cwd — unmanaged by compaction's cleanup and wrong if the
	// operator moved compaction.temp_directory to a bigger volume. The job dir
	// ({TempDirectory}/{JobID}) is already covered by both the subprocess's
	// deferred cleanup and the parent's exact cleanup; if either process
	// crashes, CleanupOrphanedTempDirs removes the leftover on startup.
	// JobID is always set by the parent (CompactPartition); skip on the
	// defensive empty case and keep DuckDB's default.
	if config.JobID != "" {
		spillDir := filepath.Join(jobTempDir(config.TempDirectory, config.JobID), "duckdb-spill")
		if err := os.MkdirAll(spillDir, 0700); err != nil {
			logger.Warn().Err(err).Str("dir", spillDir).Msg("Failed to create DuckDB spill directory; keeping DuckDB default")
		} else if _, err := db.Exec(fmt.Sprintf("SET temp_directory='%s'", escapeSQLString(spillDir))); err != nil {
			logger.Warn().Err(err).Str("dir", spillDir).Msg("Failed to set DuckDB spill directory")
		} else {
			logger.Info().Str("dir", spillDir).Msg("DuckDB spill directory configured")
		}
	}

	// Create manifest manager for crash recovery
	manifestManager := NewManifestManager(backend, logger)

	// Create and run job
	job := NewJob(&JobConfig{
		Database:        config.Database,
		Measurement:     config.Measurement,
		PartitionPath:   config.PartitionPath,
		Files:           config.Files,
		StorageBackend:  backend,
		Tier:            config.Tier,
		BatchNumber:     config.BatchNumber,
		TempDirectory:   config.TempDirectory,
		SortKeys:        config.SortKeys,
		Logger:          logger,
		DB:              db,
		ManifestManager: manifestManager,
		// Phase 4: thread cluster-mode fields through to the job. When
		// CompletionDir is empty (OSS / standalone), clusterMode() is
		// false and the completion-manifest writes are no-ops.
		JobID:                   config.JobID,
		CompletionDir:           config.CompletionDir,
		PartitionTime:           config.PartitionTime,
		ParentFinalizesManifest: config.ParentFinalizesManifest,
	})

	// Use signal-aware context so the subprocess can cancel DuckDB queries
	// when the parent kills it via SIGTERM (from exec.CommandContext).
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGTERM, syscall.SIGINT)
	defer stop()
	err = job.Run(ctx)

	result := &SubprocessJobResult{
		Success:        err == nil,
		FilesCompacted: job.FilesCompacted,
		BytesBefore:    job.BytesBefore,
		BytesAfter:     job.BytesAfter,
		// The storage key of the output (empty when the job produced none).
		// The parent's compacted-output observer keys the edge sync ledger
		// on this; the temp path would never match a storage listing.
		OutputFile:      job.OutputStorageKey,
		CompactedInputs: job.CompactedInputKeys(),
		ManifestPath:    job.RetainedManifestPath(),
	}
	if err != nil {
		result.Error = err.Error()
	}

	logger.Info().
		Bool("success", result.Success).
		Int("files_compacted", result.FilesCompacted).
		Int64("bytes_before", result.BytesBefore).
		Int64("bytes_after", result.BytesAfter).
		Msg("Compaction subprocess completed")

	// Write heap profile if profiling is enabled
	if profilingEnabled {
		logMemStats(logger, "AFTER compaction")
		writeHeapProfile(logger, "/tmp/arc_compaction_heap.pprof")
	}

	return result, nil
}

// logMemStats logs current memory statistics
func logMemStats(logger zerolog.Logger, label string) {
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	logger.Info().
		Str("label", label).
		Uint64("alloc_mb", m.Alloc/1024/1024).
		Uint64("total_alloc_mb", m.TotalAlloc/1024/1024).
		Uint64("sys_mb", m.Sys/1024/1024).
		Uint64("heap_alloc_mb", m.HeapAlloc/1024/1024).
		Uint64("heap_sys_mb", m.HeapSys/1024/1024).
		Uint64("heap_inuse_mb", m.HeapInuse/1024/1024).
		Uint32("num_gc", m.NumGC).
		Msg("Memory stats")
}

// writeHeapProfile writes a heap profile to the specified path
func writeHeapProfile(logger zerolog.Logger, path string) {
	f, err := os.Create(path)
	if err != nil {
		logger.Error().Err(err).Str("path", path).Msg("Failed to create heap profile")
		return
	}
	defer f.Close()

	// Force GC before capturing profile for accurate view
	runtime.GC()

	if err := pprof.WriteHeapProfile(f); err != nil {
		logger.Error().Err(err).Msg("Failed to write heap profile")
		return
	}
	logger.Info().Str("path", path).Msg("Heap profile written")
}

// RunJobInSubprocess executes compaction in a subprocess for memory isolation.
// The subprocess runs the same binary with the "compact" subcommand.
// When the subprocess exits, all DuckDB memory (including jemalloc arenas) is released.
// extraEnv can be used to pass additional environment variables (e.g., credentials).
func RunJobInSubprocess(ctx context.Context, config *SubprocessJobConfig, logger zerolog.Logger, extraEnv ...string) (*SubprocessJobResult, error) {
	// Serialize config to JSON
	configJSON, err := json.Marshal(config)
	if err != nil {
		return nil, fmt.Errorf("failed to serialize job config: %w", err)
	}

	// Get path to current executable
	execPath, err := os.Executable()
	if err != nil {
		return nil, fmt.Errorf("failed to get executable path: %w", err)
	}

	// Build command: arc compact --job-stdin
	// Pass config via stdin to avoid "argument list too long" errors with many files
	cmd := exec.CommandContext(ctx, execPath, "compact", "--job-stdin")

	// Pass config via stdin
	cmd.Stdin = bytes.NewReader(configJSON)

	// Set extra environment variables (e.g., Azure credentials)
	if len(extraEnv) > 0 {
		cmd.Env = append(os.Environ(), extraEnv...)
	}

	// Capture stdout and stderr separately
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	logger.Info().
		Str("partition", config.PartitionPath).
		Int("files", len(config.Files)).
		Int("config_size_kb", len(configJSON)/1024).
		Msg("Starting compaction subprocess")

	// Run subprocess
	err = cmd.Run()

	// Log stderr (contains subprocess logs). The subprocess emits structured
	// zerolog JSON, so re-emit each line at its original level instead of
	// flattening everything to INFO (which made subprocess errors appear as INF).
	if stderr.Len() > 0 {
		// Log each line separately for better formatting
		for _, line := range strings.Split(strings.TrimSpace(stderr.String()), "\n") {
			if line != "" {
				forwardSubprocessLine(logger, line)
			}
		}
	}

	if err != nil {
		// Check if it's a context cancellation
		if ctx.Err() != nil {
			return nil, fmt.Errorf("subprocess cancelled: %w", ctx.Err())
		}
		return nil, fmt.Errorf("subprocess failed: %w (stderr: %s)", err, stderr.String())
	}

	// Parse result from stdout
	var result SubprocessJobResult
	if err := json.Unmarshal(stdout.Bytes(), &result); err != nil {
		return nil, fmt.Errorf("failed to parse subprocess result: %w (stdout: %s)", err, stdout.String())
	}

	logger.Debug().
		Bool("success", result.Success).
		Int("files_compacted", result.FilesCompacted).
		Msg("Subprocess completed")

	return &result, nil
}

// forwardSubprocessLine re-emits a single line of subprocess stderr at its
// original zerolog level. The subprocess logs structured JSON, so we parse the
// "level" field and map it onto the parent logger; lines that aren't JSON (or
// have no recognizable level) fall back to INFO. The original line is preserved
// verbatim as the message so the full subprocess payload (including its own
// stack traces) is never lost.
func forwardSubprocessLine(logger zerolog.Logger, line string) {
	level := zerolog.InfoLevel
	var parsed struct {
		Level string `json:"level"`
	}
	if err := json.Unmarshal([]byte(line), &parsed); err == nil && parsed.Level != "" {
		if lvl, err := zerolog.ParseLevel(parsed.Level); err == nil {
			level = lvl
		}
	}
	logger.WithLevel(level).
		Str("subprocess", "compaction").
		Msg(line)
}

// createStorageBackendFromConfig creates a storage backend from subprocess config.
//
// This deliberately does NOT go through the shared storage.NewBackend factory
// (internal/storage/factory.go) that primary storage, the tiering cold tier and
// the backup manager use. The subprocess has a credential model of its own, on
// purpose: credentials are never serialised into the job config, so it MUST
// read them from the environment the parent set. The S3 case passes none at all
// and lets the SDK chain pick them up, and the Azure case derives
// UseManagedIdentity from whether AZURE_STORAGE_KEY is present. The factory
// itself is indifferent to credentials and its other callers simply forward
// whatever the operator configured; here the empty credential set IS the
// contract, and a regression in it surfaces as a failed compaction job in a
// separate process rather than a failed startup - the hardest place to notice
// one.
func createStorageBackendFromConfig(config *SubprocessJobConfig, logger zerolog.Logger) (storage.Backend, error) {
	switch config.StorageType {
	case "local":
		var localConfig struct {
			BasePath string `json:"base_path"`
		}
		if err := json.Unmarshal([]byte(config.StorageConfig), &localConfig); err != nil {
			return nil, fmt.Errorf("failed to parse local storage config: %w", err)
		}
		return storage.NewLocalBackend(localConfig.BasePath, logger)

	case "s3":
		// Every field S3Backend.ConfigJSON emits must be parsed and forwarded
		// here. Prefix in particular: it is applied to every key the backend
		// touches (prefixedKey), so dropping it silently reroots the subprocess
		// at the bucket root and compaction reads and writes the wrong location.
		// It defaults to empty, which is why the omission went unnoticed.
		var s3Config struct {
			Bucket    string `json:"bucket"`
			Prefix    string `json:"prefix"`
			Region    string `json:"region"`
			Endpoint  string `json:"endpoint"`
			PathStyle bool   `json:"path_style"`
			UseSSL    bool   `json:"use_ssl"`
		}
		if err := json.Unmarshal([]byte(config.StorageConfig), &s3Config); err != nil {
			return nil, fmt.Errorf("failed to parse S3 storage config: %w", err)
		}
		return storage.NewS3Backend(&storage.S3Config{
			Bucket:    s3Config.Bucket,
			Prefix:    s3Config.Prefix,
			Region:    s3Config.Region,
			Endpoint:  s3Config.Endpoint,
			PathStyle: s3Config.PathStyle,
			UseSSL:    s3Config.UseSSL,
			// Credentials come from environment variables
		}, logger)

	case "azure":
		// Same rule as the S3 case above, and for the same reason: every field
		// AzureBlobBackend.ConfigJSON emits must be parsed and forwarded here.
		// Prefix in particular is applied to every key the backend touches
		// (prefixedKey), so dropping it silently reroots the subprocess at the
		// container root and compaction reads and writes the wrong location.
		// It defaults to empty, which is why the same omission on the S3 side
		// went unnoticed.
		var azureConfig struct {
			Container   string `json:"container"`
			Prefix      string `json:"prefix"`
			AccountName string `json:"account_name"`
			Endpoint    string `json:"endpoint"`
		}
		if err := json.Unmarshal([]byte(config.StorageConfig), &azureConfig); err != nil {
			return nil, fmt.Errorf("failed to parse Azure storage config: %w", err)
		}
		// Read credentials from environment variables (set by parent process)
		accountKey := os.Getenv("AZURE_STORAGE_KEY")
		return storage.NewAzureBlobBackend(&storage.AzureBlobConfig{
			ContainerName:      azureConfig.Container,
			Prefix:             azureConfig.Prefix,
			AccountName:        azureConfig.AccountName,
			AccountKey:         accountKey,
			Endpoint:           azureConfig.Endpoint,
			UseManagedIdentity: accountKey == "", // Only use managed identity if no key provided
		}, logger)

	default:
		return nil, fmt.Errorf("unsupported storage type: %s", config.StorageType)
	}
}

// sqlErrorMarkers are deterministic DuckDB SQL failure classes: a query that
// fails to bind, resolve, or parse fails identically at any batch size, so the
// adaptive splitter must not walk its retry ladder on them.
var sqlErrorMarkers = []string{"binder error", "catalog error", "parser error"}

// memoryErrorMarkers indicate memory pressure; retrying with a smaller batch
// is exactly the right response.
var memoryErrorMarkers = []string{"out of memory", "cannot allocate", "memory allocation failed"}

// permanentErrorMarkers are failures no retry can fix: the input is gone or
// unreadable. Both streams are searched for each one - see ClassifySubprocessError.
var permanentErrorMarkers = []string{
	"no files found that match",
	"permission denied",
	"no such file",
	"access denied",
	"not found",
}

// ClassifySubprocessError determines if a subprocess error is recoverable via retry.
// Returns (recoverable, reason) where reason describes the error type.
//
// Recoverable errors (should retry with smaller batch):
//   - Segmentation faults (memory corruption, often from memory pressure)
//   - SIGKILL (exit code 137, usually OOM killer)
//   - Explicit memory errors in the error string or stderr (including DuckDB's
//     own "Out of Memory Error", which arrives via the subprocess JSON result)
//
// Non-recoverable errors (should not retry):
//   - Deterministic DuckDB SQL errors (Binder/Catalog/Parser Error) — these
//     fail identically at any batch size
//   - Permission denied
//   - File not found
//   - Access denied
func ClassifySubprocessError(err error, stderr string) (recoverable bool, reason string) {
	if err == nil {
		return false, ""
	}

	errStr := err.Error()
	errLower := strings.ToLower(errStr)
	stderrLower := strings.ToLower(stderr)

	// Process-level evidence first: a real, actionable SQL error always arrives
	// via the subprocess JSON result (exit 0, success=false), so it can never
	// co-occur with a signal or OOM exit code. A crashed subprocess, however,
	// embeds its whole stderr in the error string — including warn lines that
	// may quote SQL error text — so a signal/exit-code match must win over the
	// string markers below or a crash-after-warn would misclassify as permanent.

	// Check for signals (segfault, killed)
	if strings.Contains(errStr, "signal:") {
		if strings.Contains(errStr, "segmentation fault") {
			return true, "segfault"
		}
		if strings.Contains(errStr, "killed") {
			return true, "killed"
		}
	}

	// Check exit codes for OOM (137 = SIGKILL, often OOM killer)
	if exitErr, ok := err.(*exec.ExitError); ok {
		exitCode := exitErr.ExitCode()
		if exitCode == 137 {
			return true, "oom_killed"
		}
		// Exit code 139 is SIGSEGV
		if exitCode == 139 {
			return true, "segfault"
		}
	}

	// Deterministic DuckDB SQL errors — permanent at any batch size, so the
	// splitter's retry ladder (each rung re-downloads the whole batch) is pure
	// waste. These arrive via the JSON result path, so they appear in err
	// rather than stderr; check both.
	for _, marker := range sqlErrorMarkers {
		if strings.Contains(errLower, marker) || strings.Contains(stderrLower, marker) {
			return false, "sql_error"
		}
	}

	// Check for memory-related errors in either stream.
	for _, marker := range memoryErrorMarkers {
		if strings.Contains(errLower, marker) || strings.Contains(stderrLower, marker) {
			return true, "memory_error"
		}
	}

	// Non-recoverable errors - don't waste time retrying. Checked against BOTH
	// streams, like memoryErrorMarkers above: a subprocess reports a missing
	// input through stderr, but the parent's own wrapped error carries it in
	// err, and a marker tested against only one stream leaves the other
	// classified "unknown" and spending the full retry budget on a failure that
	// cannot succeed (#969 - an input deleted mid-job cost ~15 subprocess
	// launches before this was symmetric).
	for _, marker := range permanentErrorMarkers {
		if strings.Contains(errLower, marker) || strings.Contains(stderrLower, marker) {
			return false, "permanent_error"
		}
	}

	// Default: treat unknown errors as potentially recoverable once
	// This allows one retry for transient issues
	return true, "unknown"
}
